import { field } from "@futurity/atlas-connector";
import type { EsbCoreObject } from "./types";

// ESB Core API 2.0.0 publishes these read-only collection contracts at developers.esb.co.id/esb-core/api_data.json.
export const ESB_CORE_CATALOG: EsbCoreObject[] = [
  {
    name: "advance_payments",
    path: "/purchase/advance-payment",
    description: "Advance payments",
    mode: "paged",
    primaryKey: "advancePaymentNum",
    columns: [
      field("advancePaymentNum", "string", { nullable: false, unique: true, description: "Advance Payment Number" }),
      field("advancePaymentDate", "date", { nullable: true, description: "Advance Payment Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("currencyID", "number", { nullable: true, description: "Currency ID" }),
      field("currencySign", "string", { nullable: true, description: "Currency Sign" }),
      field("supplierID", "number", { nullable: true, description: "Supplier ID" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("purchaseNum", "string", { nullable: true, description: "Purchase Number" }),
      field("paymentTotal", "decimal", { nullable: true, description: "Payment Total" }),
      field("usedAdvanceTotal", "decimal", { nullable: true, description: "Used Advance Total" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("hasApproval", "boolean", { nullable: true, description: "Whether approval flow is active" }),
      field("linkAdvanceNumEsbGoods", "string", { nullable: true, description: "Link to ESB Goods Advance Number" }),
      field("createdBy", "string", { nullable: true, description: "Username who created the record" }),
    ],
  },
  {
    name: "budget_adjustments",
    path: "/budget/budget-adjustment",
    description: "Budget adjustments",
    mode: "paged",
    primaryKey: "budgetAdjustmentNum",
    columns: [
      field("budgetAdjustmentNum", "string", { nullable: false, unique: true, description: "Budget Adjustment Number" }),
      field("budgetNum", "string", { nullable: true, description: "Budget Number" }),
      field("adjustmentType", "string", { nullable: true, description: "Adjustment Type Name: Increase or Decrease" }),
      field("coaNo", "string", { nullable: true, description: "COA Number" }),
      field("amount", "number", { nullable: true, description: "Adjustment Amount" }),
      field("transactionDate", "date", { nullable: true, description: "Transaction Date" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("createdBy", "string", { nullable: true, description: "Created By" }),
      field("costCenter", "string", { nullable: true, description: "Cost Center Name" }),
      field("branch", "string", { nullable: true, description: "Branch Name" }),
    ],
  },
  {
    name: "budget_allocations",
    path: "/budget/budget-allocate",
    description: "Budget allocations",
    mode: "paged",
    primaryKey: "budgetAdjustmentNum",
    columns: [
      field("budgetAdjustmentNum", "string", { nullable: false, unique: true, description: "Budget Allocate Number" }),
      field("budgetNum", "string", { nullable: true, description: "Budget Number" }),
      field("transactionDate", "date", { nullable: true, description: "Transaction Date" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("createdBy", "string", { nullable: true, description: "Created By" }),
    ],
  },
  {
    name: "budgets",
    path: "/budgets",
    description: "Budgets",
    mode: "paged",
    primaryKey: "budgetNum",
    columns: [
      field("budgetNum", "string", { nullable: false, unique: true, description: "Budget Number" }),
      field("budgetPlanNum", "string", { nullable: true, description: "Budget Plan Number" }),
      field("budgetPlanName", "string", { nullable: true, description: "Budget Plan Name" }),
      field("periodTypeID", "number", { nullable: true, description: "Period Type ID" }),
      field("periodName", "string", { nullable: true, description: "Period Type Name" }),
      field("startPeriod", "string", { nullable: true, description: "Start Period" }),
      field("endPeriod", "string", { nullable: true, description: "End Period" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("createdBy", "string", { nullable: true, description: "Created By" }),
      field("canEdit", "boolean", { nullable: true, description: "Can Edit flag" }),
    ],
  },
  {
    name: "budget_plans",
    path: "/budget-plan",
    description: "Budget plans",
    mode: "paged",
    primaryKey: "budgetPlanNum",
    columns: [
      field("budgetPlanNum", "string", { nullable: false, unique: true, description: "Budget Plan Number" }),
      field("budgetPlanName", "string", { nullable: true, description: "Budget Plan Name" }),
      field("periodTypeID", "number", { nullable: true, description: "Period Type ID: 1 for Monthly, 2 for Yearly" }),
      field("periodType", "string", { nullable: true, description: "Period Type Name" }),
      field("startPeriodDate", "string", { nullable: true, description: "Start Period Date" }),
      field("endPeriodDate", "string", { nullable: true, description: "End Period Date" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("createdBy", "string", { nullable: true, description: "Created By" }),
      field("statusID", "number", { nullable: true, description: "Status ID: 1 for New, 3 for Authorized" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("canEdit", "boolean", { nullable: true, description: "Flag whether data can be edited" }),
    ],
  },
  {
    name: "employee_advance_payments",
    path: "/employee/employee-advance-payment",
    description: "Employee advance payments",
    mode: "paged",
    primaryKey: "employeeAdvanceNum",
    columns: [
      field("employeeAdvanceNum", "string", { nullable: false, unique: true, description: "Advance payment number with EA prefix" }),
      field("employeeAdvanceDate", "date", { nullable: true, description: "Advance payment date" }),
      field("dueDay", "number", { nullable: true, description: "Number of days until due" }),
      field("employeeAdvanceDueDate", "date", { nullable: true, description: "Due date" }),
      field("employeeCode", "string", { nullable: true, description: "Employee code" }),
      field("employeeName", "string", { nullable: true, description: "Employee name" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch name" }),
      field("currencyID", "number", { nullable: true, description: "Currency ID" }),
      field("currencySign", "string", { nullable: true, description: "Currency sign" }),
      field("employeeAdvanceTotal", "decimal", { nullable: true, description: "Advance total amount" }),
      field("rate", "decimal", { nullable: true, description: "Exchange rate" }),
      field("statusID", "number", { nullable: true, description: "Status ID: 1 for New, 2 for Rejected, 3 for Authorized, 27 for Released" }),
      field("statusName", "string", { nullable: true, description: "Status name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional information" }),
    ],
  },
  {
    name: "goods_deliveries",
    path: "/inventory/goods-delivery",
    description: "Goods deliveries",
    mode: "paged",
    columns: [
      field("goodsDeliveryNum", "string", { nullable: true, description: "Goods Delivery Number" }),
      field("goodsDeliveryDate", "date", { nullable: true, description: "Goods Delivery Date" }),
      field("transType", "string", { nullable: true, description: "Transaction Type" }),
      field("referenceNumber", "string", { nullable: true, description: "Reference Number" }),
      field("originBranchID", "number", { nullable: true, description: "Origin Branch ID" }),
      field("originBranchName", "string", { nullable: true, description: "Origin Branch Name" }),
      field("destinationBranchID", "number", { nullable: true, description: "Destination Branch ID" }),
      field("destBranchName", "string", { nullable: true, description: "Destination Branch Name" }),
      field("customerName", "string", { nullable: true, description: "Customer Name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
  {
    name: "goods_receipts",
    path: "/inventory/goods-receipt",
    description: "Goods receipts",
    mode: "paged",
    primaryKey: "goodsReceiptNum",
    columns: [
      field("goodsReceiptNum", "string", { nullable: false, unique: true, description: "Goods Receipt Number" }),
      field("goodsReceiptDate", "date", { nullable: true, description: "Goods Receipt Date" }),
      field("linkGoodsReceiptNumEsbGoods", "string", { nullable: true, description: "Goods Receipt Number ESB Goods" }),
      field("refNum", "string", { nullable: true, description: "Reference Number" }),
      field("transType", "string", { nullable: true, description: "Transaction Type" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("locationID", "number", { nullable: true, description: "Location ID" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("sourceName", "string", { nullable: true, description: "Source Name" }),
      field("createdBy", "string", { nullable: true, description: "Created By" }),
    ],
  },
  {
    name: "goods_transfer_requests",
    path: "/inventory/goods-transfer-request",
    description: "Goods transfer requests",
    mode: "paged",
    primaryKey: "transferNum",
    columns: [
      field("transferNum", "string", { nullable: false, unique: true, description: "Goods Transfer Request Number" }),
      field("transferDate", "date", { nullable: true, description: "Goods Transfer Request Date" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("originBranch", "string", { nullable: true, description: "Origin Branch" }),
      field("destinationBranch", "string", { nullable: true, description: "Destination Branch" }),
      field("purchaseRequestNum", "string", { nullable: true, description: "Purchase Request Number" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
  {
    name: "item_journals",
    path: "/inventory/item-journal",
    description: "Inventory item journals",
    mode: "paged",
    primaryKey: "itemJournalNum",
    columns: [
      field("itemJournalNum", "string", { nullable: false, unique: true, description: "Item Journal Number" }),
      field("itemJournalDate", "datetime", { nullable: true, description: "Item Journal Date in ISO 8601 format with timezone" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("locationID", "number", { nullable: true, description: "Location ID" }),
      field("locationName", "string", { nullable: true, description: "Location Name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
  {
    name: "purposes",
    path: "/purpose",
    description: "Accounting purposes",
    mode: "paged",
    primaryKey: "purposeID",
    columns: [
      field("purposeID", "number", { nullable: false, unique: true, description: "Purpose ID" }),
      field("purposeName", "string", { nullable: true, description: "Purpose Name" }),
      field("purposeAccount", "string", { nullable: true, description: "Account Name on purpose" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Purpose" }),
    ],
  },
  {
    name: "bills_of_material",
    path: "/product/bom",
    description: "Bills of material",
    mode: "paged",
    primaryKey: "bomID",
    columns: [
      field("bomID", "number", { nullable: false, unique: true, description: "Bill of Material ID" }),
      field("bomName", "string", { nullable: true, description: "Bill of Material Name" }),
      field("bomCode", "string", { nullable: true, description: "Bill of Material Code" }),
      field("bomTypeID", "number", { nullable: true, description: "Bill of Material Type ID" }),
      field("bomTypeName", "string", { nullable: true, description: "Bill of Material Type Name" }),
      field("productName", "string", { nullable: true, description: "Product Name" }),
      field("uomName", "string", { nullable: true, description: "Unit of Material Name" }),
      field("notes", "string", { nullable: true, description: "Bill of Material notes" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Bill of Material - 1: Active - 0: Not Active" }),
    ],
  },
  {
    name: "categories",
    path: "/product/category",
    description: "Product categories",
    mode: "paged",
    primaryKey: "categoryID",
    columns: [
      field("categoryID", "number", { nullable: false, unique: true, description: "Category ID" }),
      field("categoryName", "string", { nullable: true, description: "Category Name" }),
      field("categoryTypeID", "number", { nullable: true, description: "Category Type ID" }),
      field("categoryTypeName", "string", { nullable: true, description: "Category Type Name" }),
      field("notes", "string", { nullable: true, description: "Category notes" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Category - 1: Active - 0: Not Active" }),
    ],
  },
  {
    name: "branches",
    path: "/branch",
    description: "Branches available to the authenticated ESB company",
    mode: "direct",
    primaryKey: "branchID",
    columns: [
      field("branchID", "number", { nullable: false, unique: true, description: "Branch ID" }),
      field("branchCode", "string", { nullable: true, description: "Branch Code" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
    ],
  },
  {
    name: "locations",
    path: "/location",
    description: "Inventory locations",
    mode: "direct",
    primaryKey: "locationID",
    columns: [
      field("locationID", "number", { nullable: false, unique: true, description: "Location ID" }),
      field("locationName", "string", { nullable: true, description: "Location Name" }),
    ],
  },
  {
    name: "cost_centers",
    path: "/cost-center",
    description: "Cost centers",
    mode: "direct",
    primaryKey: "ID",
    columns: [
      field("ID", "number", { nullable: false, unique: true, description: "Cost Center ID" }),
      field("costCenter", "string", { nullable: true, description: "Cost Center Code" }),
      field("costCenterName", "string", { nullable: true, description: "Cost Center Name" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Cost Center" }),
      field("createdBy", "string", { nullable: true, description: "Username who create cost center" }),
      field("createdDate", "datetime", { nullable: true, description: "Date and time cost center created" }),
      field("editedBy", "string", { nullable: true, description: "Username who edited cost center last time" }),
      field("editedDate", "datetime", { nullable: true, description: "Date and time cost center last edited" }),
    ],
  },
  {
    name: "customer_pricelists",
    path: "/customer-pricelist",
    description: "Customer price lists",
    mode: "paged",
    primaryKey: "ID",
    columns: [
      field("ID", "number", { nullable: false, unique: true, description: "Customer Pricelist ID" }),
      field("priceDate", "datetime", { nullable: true, description: "Customer Pricelist active date" }),
      field("customerName", "string", { nullable: true, description: "Customer Name" }),
      field("productName", "string", { nullable: true, description: "Product Name" }),
      field("productCode", "string", { nullable: true, description: "Product Code" }),
      field("uomName", "string", { nullable: true, description: "Unit name" }),
      field("currencyName", "string", { nullable: true, description: "Currency Name" }),
      field("expireDate", "datetime", { nullable: true, description: "Expire Date" }),
      field("price", "number", { nullable: true, description: "Customer Pricelist product price" }),
    ],
  },
  {
    name: "customers",
    path: "/customer",
    description: "Customers",
    mode: "paged",
    primaryKey: "customerID",
    columns: [
      field("customerID", "number", { nullable: false, unique: true, description: "Customer ID" }),
      field("customerName", "string", { nullable: true, description: "Customer Name" }),
      field("customerCode", "string", { nullable: true, description: "Customer Code" }),
      field("customerCategoryID", "string", { nullable: true, description: "Customer Category ID" }),
      field("customerCategoryName", "string", { nullable: true, description: "Customer Category Name" }),
      field("paymentDueDays", "number", { nullable: true, description: "Payment Due Days" }),
      field("address", "string", { nullable: true, description: "Customer Address" }),
      field("picName", "string", { nullable: true, description: "PIC Name" }),
      field("picPhone", "string", { nullable: true, description: "PIC Phone" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Customer" }),
      field("lockVat", "boolean", { nullable: true, description: "Flag setting for lock Vat in transaction" }),
    ],
  },
  {
    name: "document_templates",
    path: "/document-template",
    description: "Document templates",
    mode: "paged",
    primaryKey: "requestTemplateID",
    columns: [
      field("requestTemplateID", "number", { nullable: false, unique: true, description: "Request Template ID" }),
      field("requestTemplateName", "string", { nullable: true, description: "Request Template Name" }),
      field("branchNames", "string", { nullable: true, description: "Branch Name" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Bill of Material - 1: Active - 0: Not Active" }),
    ],
  },
  {
    name: "pricelists",
    path: "/pricelist",
    description: "Supplier price lists",
    mode: "paged",
    primaryKey: "ID",
    columns: [
      field("ID", "number", { nullable: false, unique: true, description: "Pricelist ID" }),
      field("priceDate", "date", { nullable: true, description: "Pricelist active date" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("productName", "string", { nullable: true, description: "Product Name" }),
      field("productCode", "string", { nullable: true, description: "Product Code" }),
      field("unit", "string", { nullable: true, description: "Unit name" }),
      field("currencyName", "string", { nullable: true, description: "Currency Name" }),
      field("price", "number", { nullable: true, description: "Pricelist product price" }),
    ],
  },
  {
    name: "products",
    path: "/product/list",
    description: "Products",
    mode: "paged",
    primaryKey: "productID",
    columns: [
      field("productID", "number", { nullable: false, unique: true, description: "Product ID" }),
      field("productName", "string", { nullable: true, description: "Product Name" }),
      field("productCode", "string", { nullable: true, description: "Product Code" }),
      field("categoryID", "number", { nullable: true, description: "Category Type ID" }),
      field("subCategoryID", "number", { nullable: true, description: "Sub Category ID" }),
      field("subCategoryName", "string", { nullable: true, description: "Sub Category Name" }),
      field("bomID", "number", { nullable: true, description: "Bill of Material ID" }),
      field("bomName", "string", { nullable: true, description: "Bill of Material Name" }),
      field("categoryTypeID", "number", { nullable: true, description: "Category Type ID" }),
      field("categoryTypeName", "string", { nullable: true, description: "Category Type Name" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Bill of Material - 1: Active - 0: Not Active" }),
      field("categoryName", "string", { nullable: true, description: "" }),
    ],
  },
  {
    name: "subcategories",
    path: "/product/sub-category",
    description: "Product subcategories",
    mode: "paged",
    primaryKey: "subCategoryID",
    columns: [
      field("subCategoryID", "number", { nullable: false, unique: true, description: "Sub Category ID" }),
      field("subCategoryName", "string", { nullable: true, description: "Sub Category Name" }),
      field("notes", "string", { nullable: true, description: "Sub Category notes" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Category - 1: Active - 0: Not Active" }),
    ],
  },
  {
    name: "supplier_categories",
    path: "/supplier/category/list",
    description: "Supplier categories",
    mode: "paged",
    primaryKey: "supplierCategoryID",
    columns: [
      field("supplierCategoryID", "number", { nullable: false, unique: true, description: "Supplier Category ID" }),
      field("supplierCategoryName", "string", { nullable: true, description: "Supplier Category Name" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Supplier Category: 1 Active, 0 Not Active" }),
    ],
  },
  {
    name: "suppliers",
    path: "/supplier",
    description: "Suppliers",
    mode: "paged",
    primaryKey: "supplierID",
    columns: [
      field("supplierID", "number", { nullable: false, unique: true, description: "Supplier ID" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("address", "string", { nullable: true, description: "Supplier Address" }),
      field("supplierCode", "string", { nullable: true, description: "Supplier Code" }),
      field("dueDate", "number", { nullable: true, description: "Credit Terms in Days" }),
      field("flagActive", "boolean", { nullable: true, description: "Flag setting for Active or not Supplier Category" }),
      field("contactPerson", "string", { nullable: true, description: "Supplier PIC Name" }),
      field("cellPhone", "string", { nullable: true, description: "Supplier PIC Phone Number" }),
      field("category", "string", { nullable: true, description: "Supplier Category Name" }),
      field("supplierCategoryID", "number", { nullable: true, description: "Supplier Category ID" }),
    ],
  },
  {
    name: "units",
    path: "/units",
    description: "Units of measure",
    mode: "direct",
    primaryKey: "uomID",
    columns: [
      field("uomID", "number", { nullable: false, unique: true, description: "Unit of Material ID" }),
      field("uomName", "string", { nullable: true, description: "Unit of Material Name" }),
    ],
  },
  {
    name: "material_deliveries",
    path: "/production/material-delivery",
    description: "Production material deliveries",
    mode: "paged",
    primaryKey: "materialDeliveryNum",
    columns: [
      field("materialDeliveryNum", "string", { nullable: false, unique: true, description: "Material Delivery Number" }),
      field("materialDeliveryDate", "datetime", { nullable: true, description: "Material Delivery Date" }),
      field("productionOrderNum", "string", { nullable: true, description: "Production Order Number" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
  {
    name: "memorial_journals",
    path: "/accounting/memorial-journal",
    description: "Memorial journals",
    mode: "paged",
    primaryKey: "memorialJournalNum",
    columns: [
      field("memorialJournalNum", "string", { nullable: false, unique: true, description: "Memorial Journal number with MJ prefix" }),
      field("memorialJournalDate", "datetime", { nullable: true, description: "Memorial Journal date" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional information" }),
      field("statusID", "number", { nullable: true, description: "Status ID: 1 for New, 2 for Rejected, 3 for Authorized, 38 for Waiting For Approval" }),
      field("statusName", "string", { nullable: true, description: "Status name" }),
      field("createdBy", "string", { nullable: true, description: "Creator username" }),
      field("approval", "boolean", { nullable: true, description: "Whether approval flow is configured for this transaction" }),
    ],
  },
  {
    name: "production_orders",
    path: "/production/production-order",
    description: "Production orders",
    mode: "paged",
    primaryKey: "productionOrderNum",
    columns: [
      field("productionOrderNum", "string", { nullable: false, unique: true, description: "Production Order Number" }),
      field("productionOrderDate", "datetime", { nullable: true, description: "Production Order Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("bomTypeID", "number", { nullable: true, description: "Bill of material type ID" }),
      field("bomTypeName", "string", { nullable: true, description: "Bill of material type name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
  {
    name: "production_results",
    path: "/production/production-result",
    description: "Production results",
    mode: "paged",
    primaryKey: "productionResultNum",
    columns: [
      field("productionResultNum", "string", { nullable: false, unique: true, description: "Production Result Number" }),
      field("productionResultDate", "datetime", { nullable: true, description: "Production Result Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("productionOrderDetailID", "number", { nullable: true, description: "Production Order Detail ID" }),
      field("productionOrderNum", "string", { nullable: true, description: "Production Result Number" }),
      field("bomID", "number", { nullable: true, description: "Bill of material ID" }),
      field("bomName", "string", { nullable: true, description: "Bill of material name" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
    ],
  },
  {
    name: "purchase_invoices",
    path: "/purchase/purchase-invoices",
    description: "Purchase invoices",
    mode: "paged",
    primaryKey: "purchaseInvoiceNum",
    columns: [
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("createdBy", "string", { nullable: true, description: "Username who created the record" }),
      field("createdByFullName", "string", { nullable: true, description: "Full name of the user who created the record" }),
      field("currencyID", "number", { nullable: true, description: "Currency ID" }),
      field("currencySign", "string", { nullable: true, description: 'Currency Symbol, such as "IDR" or "USD"' }),
      field("invoiceTotal", "number", { nullable: true, description: "Total invoice amount" }),
      field("linkInvoiceNumEsbGoods", "string", { nullable: true, description: "Linked ESB Goods Invoice Number when available" }),
      field("overDue", "number", { nullable: true, description: "Days overdue from due date" }),
      field("purchaseInvoiceDate", "date", { nullable: true, description: "Purchase Invoice Date" }),
      field("purchaseInvoiceDueDate", "date", { nullable: true, description: "Purchase Invoice Due Date" }),
      field("purchaseInvoiceNum", "string", { nullable: false, unique: true, description: "Purchase Invoice Number" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: 'Status Name, such as "New", "Authorized", "Rejected", "Full Paid", or "Draft"' }),
      field("supplierID", "number", { nullable: true, description: "Supplier ID" }),
      field("supplierInvoiceNum", "string", { nullable: true, description: "Supplier Invoice Number when available" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional information" }),
    ],
  },
  {
    name: "purchase_orders",
    path: "/purchase/purchase-order",
    description: "Purchase orders",
    mode: "paged",
    primaryKey: "purchaseNum",
    columns: [
      field("purchaseNum", "string", { nullable: false, unique: true, description: "Purchase Order Number" }),
      field("purchaseDate", "datetime", { nullable: true, description: "Purchase Order Date" }),
      field("requiredDate", "datetime", { nullable: true, description: "Purchase Order Required Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("supplierID", "number", { nullable: true, description: "Supplier ID" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("currencyID", "number", { nullable: true, description: "Currency ID" }),
      field("currencySign", "string", { nullable: true, description: "Currency Sign" }),
      field("purchaseRequestNums", "string", { nullable: true, description: "Purchase Request Number" }),
      field("linkPurchaseNumEsbGoods", "string", { nullable: true, description: "Link Purchase ESB Goods" }),
      field("purchaseTotal", "decimal", { nullable: true, description: "" }),
      field("printedBy", "string", { nullable: true, description: "Printed By" }),
      field("printedDate", "string", { nullable: true, description: "Printed Date" }),
      field("emailedBy", "string", { nullable: true, description: "Emailed By" }),
      field("emailedDate", "datetime", { nullable: true, description: "Emailed Date" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Info" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("approval", "string", { nullable: true, description: "Approval" }),
      field("mapSupplierLink", "string", { nullable: true, description: "Map Supplier Link" }),
    ],
  },
  {
    name: "purchase_requests",
    path: "/purchase/purchase-request",
    description: "Purchase requests",
    mode: "paged",
    primaryKey: "purchaseRequestNum",
    columns: [
      field("purchaseRequestNum", "string", { nullable: false, unique: true, description: "Purchase Request Number" }),
      field("purchaseRequestDate", "date", { nullable: true, description: "Purchase Request Date" }),
      field("requiredDate", "date", { nullable: true, description: "Required Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("createdDate", "date", { nullable: true, description: "Created Date" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("requestTemplateID", "number", { nullable: true, description: "Request Template ID" }),
    ],
  },
  {
    name: "purchase_returns",
    path: "/purchases/purchase-return",
    description: "Purchase returns",
    mode: "paged",
    primaryKey: "purchaseReturnNum",
    columns: [
      field("purchaseReturnNum", "string", { nullable: false, unique: true, description: "Purchase Return Number" }),
      field("purchaseReturnDate", "date", { nullable: true, description: "Purchase Return Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("supplierID", "number", { nullable: true, description: "Supplier ID" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: 'Status Name, such as "New", "Rejected", "Authorized", "Full Paid", or "Draft"' }),
    ],
  },
  {
    name: "receipts",
    path: "/receipt",
    description: "Customer receipts",
    mode: "paged",
    primaryKey: "receiptNum",
    columns: [
      field("receiptNum", "string", { nullable: false, unique: true, description: "Receipt Number" }),
      field("receiptDate", "date", { nullable: true, description: "Receipt Date" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("customerName", "string", { nullable: true, description: "Customer Name" }),
      field("paymentType", "string", { nullable: true, description: "Type of Payment" }),
      field("grandTotal", "decimal", { nullable: true, description: "Grand Total Receipt" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("hasApproval", "boolean", { nullable: true, description: "Receipt has approval or not" }),
    ],
  },
  {
    name: "sales_orders",
    path: "/sales/product-sales",
    description: "Sales orders",
    mode: "paged",
    primaryKey: "productSalesNum",
    columns: [
      field("additionalInfo", "string", { nullable: true, description: "Additional Info" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("createdBy", "string", { nullable: true, description: "Username who create Sales Order" }),
      field("customerAddress", "string", { nullable: true, description: "Customer Address" }),
      field("customerID", "number", { nullable: true, description: "Customer ID" }),
      field("customerName", "string", { nullable: true, description: "Customer Name" }),
      field("currencySign", "string", { nullable: true, description: "Currency Sign" }),
      field("linkPurchaseNum", "string", { nullable: true, description: "Reference Number" }),
      field("productSalesTypeID", "number", { nullable: true, description: "Sales Order Type ID" }),
      field("requiredDate", "date", { nullable: true, description: "Sales Order Required Date" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("productSalesDate", "date", { nullable: true, description: "Sales Order Date" }),
      field("productSalesNum", "string", { nullable: false, unique: true, description: "Sales Order Number" }),
      field("productSalesTotal", "decimal", { nullable: true, description: "Sales Order Total" }),
    ],
  },
  {
    name: "simple_manufacturing",
    path: "/production/simple-manufacturing",
    description: "Simple manufacturing transactions",
    mode: "paged",
    primaryKey: "simpleManufacturingNum",
    columns: [
      field("simpleManufacturingNum", "string", { nullable: false, unique: true, description: "Simple Manufacturing Number" }),
      field("simpleManufacturingDate", "datetime", { nullable: true, description: "Simple Manufacturing Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("bomTypeID", "number", { nullable: true, description: "Bill of Material Type ID" }),
      field("bomTypeName", "string", { nullable: true, description: "Bill of Material Type Name" }),
      field("bomID", "number", { nullable: true, description: "Bill of Material ID" }),
      field("bomName", "string", { nullable: true, description: "Bill of Material Name" }),
      field("bomCode", "string", { nullable: true, description: "Bill of Material Code" }),
      field("manufacturingQty", "decimal", { nullable: true, description: "Manufacturing Quantity" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
  {
    name: "simple_purchases",
    path: "/purchase/simple-purchase",
    description: "Simple purchase transactions",
    mode: "paged",
    primaryKey: "cashPurchaseNum",
    columns: [
      field("cashPurchaseNum", "string", { nullable: false, unique: true, description: "Simple Purchase Number" }),
      field("cashPurchaseDate", "datetime", { nullable: true, description: "Simple Purchase Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("supplierID", "number", { nullable: true, description: "Supplier ID" }),
      field("supplierName", "string", { nullable: true, description: "Supplier Name" }),
      field("currencySign", "string", { nullable: true, description: "Currency Name" }),
      field("cashPurchaseTotal", "decimal", { nullable: true, description: "Cash Purchase Total" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("approval", "string", { nullable: true, description: "Approval" }),
    ],
  },
  {
    name: "simple_sales",
    path: "/sales/simple-product-sales",
    description: "Simple sales transactions",
    mode: "paged",
    primaryKey: "simpleProductSalesNum",
    columns: [
      field("simpleProductSalesNum", "string", { nullable: false, unique: true, description: "Simple Sales Number" }),
      field("simpleProductSalesDate", "datetime", { nullable: true, description: "Transaction Date" }),
      field("branchID", "number", { nullable: true, description: "Branch ID" }),
      field("branchName", "string", { nullable: true, description: "Branch Name" }),
      field("customerID", "number", { nullable: true, description: "Customer ID" }),
      field("customerName", "string", { nullable: true, description: "Customer Name" }),
      field("simpleProductSalesTotal", "decimal", { nullable: true, description: "Transaction Total Amount" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
      field("currencySign", "string", { nullable: true, description: "Currency Sign" }),
      field("vatInvoiceNum", "string", { nullable: true, description: "VAT Invoice Number" }),
      field("paymentID", "number", { nullable: true, description: "Payment Type ID" }),
      field("paymentName", "string", { nullable: true, description: "Payment Type Name" }),
    ],
  },
  {
    name: "simple_transfers",
    path: "/simple-transfer",
    description: "Simple inventory transfers",
    mode: "paged",
    primaryKey: "simpleTransferNum",
    columns: [
      field("simpleTransferNum", "string", { nullable: false, unique: true, description: "Simple Transfer Number" }),
      field("simpleTransferDate", "date", { nullable: true, description: "Simple Transfer Date" }),
      field("originLocationName", "string", { nullable: true, description: "Origin Location name" }),
      field("destinationLocationName", "string", { nullable: true, description: "Destination Location Name" }),
      field("destinationLocationID", "number", { nullable: true, description: "Destination Location ID" }),
      field("additionalInfo", "string", { nullable: true, description: "Additional Information" }),
      field("statusID", "number", { nullable: true, description: "Status ID" }),
      field("statusName", "string", { nullable: true, description: "Status Name" }),
    ],
  },
];

for (const object of ESB_CORE_CATALOG) {
  if (object.primaryKey && !object.columns.some((column) => column.name === object.primaryKey)) {
    throw new Error(`ESB Core primary key '${object.name}.${object.primaryKey}' is not a declared field`);
  }
}
