import type { EsbCoreObject } from "./types";

// ESB Core API 2.0.0 publishes these read-only collection contracts at developers.esb.co.id/esb-core/api_data.json.
export const ESB_CORE_CATALOG: EsbCoreObject[] = [
  {
    name: "advance_payments",
    path: "/purchase/advance-payment",
    description: "Advance payments",
    mode: "paged",
    primaryKey: "advancePaymentNum",
    columns: [
      {
        name: "advancePaymentNum",
        type: "string",
        nullable: false,
        description: "Advance Payment Number",
      },
      {
        name: "advancePaymentDate",
        type: "date",
        nullable: true,
        description: "Advance Payment Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "currencyID",
        type: "number",
        nullable: true,
        description: "Currency ID",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: "Currency Sign",
      },
      {
        name: "supplierID",
        type: "number",
        nullable: true,
        description: "Supplier ID",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "purchaseNum",
        type: "string",
        nullable: true,
        description: "Purchase Number",
      },
      {
        name: "paymentTotal",
        type: "decimal",
        nullable: true,
        description: "Payment Total",
      },
      {
        name: "usedAdvanceTotal",
        type: "decimal",
        nullable: true,
        description: "Used Advance Total",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "hasApproval",
        type: "boolean",
        nullable: true,
        description: "Whether approval flow is active",
      },
      {
        name: "linkAdvanceNumEsbGoods",
        type: "string",
        nullable: true,
        description: "Link to ESB Goods Advance Number",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Username who created the record",
      },
    ],
  },
  {
    name: "budget_adjustments",
    path: "/budget/budget-adjustment",
    description: "Budget adjustments",
    mode: "paged",
    primaryKey: "budgetAdjustmentNum",
    columns: [
      {
        name: "budgetAdjustmentNum",
        type: "string",
        nullable: false,
        description: "Budget Adjustment Number",
      },
      {
        name: "budgetNum",
        type: "string",
        nullable: true,
        description: "Budget Number",
      },
      {
        name: "adjustmentType",
        type: "string",
        nullable: true,
        description: "Adjustment Type Name: Increase or Decrease",
      },
      {
        name: "coaNo",
        type: "string",
        nullable: true,
        description: "COA Number",
      },
      {
        name: "amount",
        type: "number",
        nullable: true,
        description: "Adjustment Amount",
      },
      {
        name: "transactionDate",
        type: "date",
        nullable: true,
        description: "Transaction Date",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Created By",
      },
      {
        name: "costCenter",
        type: "string",
        nullable: true,
        description: "Cost Center Name",
      },
      {
        name: "branch",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
    ],
  },
  {
    name: "budget_allocations",
    path: "/budget/budget-allocate",
    description: "Budget allocations",
    mode: "paged",
    primaryKey: "budgetAdjustmentNum",
    columns: [
      {
        name: "budgetAdjustmentNum",
        type: "string",
        nullable: false,
        description: "Budget Allocate Number",
      },
      {
        name: "budgetNum",
        type: "string",
        nullable: true,
        description: "Budget Number",
      },
      {
        name: "transactionDate",
        type: "date",
        nullable: true,
        description: "Transaction Date",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Created By",
      },
    ],
  },
  {
    name: "budgets",
    path: "/budgets",
    description: "Budgets",
    mode: "paged",
    primaryKey: "budgetNum",
    columns: [
      {
        name: "budgetNum",
        type: "string",
        nullable: false,
        description: "Budget Number",
      },
      {
        name: "budgetPlanNum",
        type: "string",
        nullable: true,
        description: "Budget Plan Number",
      },
      {
        name: "budgetPlanName",
        type: "string",
        nullable: true,
        description: "Budget Plan Name",
      },
      {
        name: "periodTypeID",
        type: "number",
        nullable: true,
        description: "Period Type ID",
      },
      {
        name: "periodName",
        type: "string",
        nullable: true,
        description: "Period Type Name",
      },
      {
        name: "startPeriod",
        type: "string",
        nullable: true,
        description: "Start Period",
      },
      {
        name: "endPeriod",
        type: "string",
        nullable: true,
        description: "End Period",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Created By",
      },
      {
        name: "canEdit",
        type: "boolean",
        nullable: true,
        description: "Can Edit flag",
      },
    ],
  },
  {
    name: "budget_plans",
    path: "/budget-plan",
    description: "Budget plans",
    mode: "paged",
    primaryKey: "budgetPlanNum",
    columns: [
      {
        name: "budgetPlanNum",
        type: "string",
        nullable: false,
        description: "Budget Plan Number",
      },
      {
        name: "budgetPlanName",
        type: "string",
        nullable: true,
        description: "Budget Plan Name",
      },
      {
        name: "periodTypeID",
        type: "number",
        nullable: true,
        description: "Period Type ID: 1 for Monthly, 2 for Yearly",
      },
      {
        name: "periodType",
        type: "string",
        nullable: true,
        description: "Period Type Name",
      },
      {
        name: "startPeriodDate",
        type: "string",
        nullable: true,
        description: "Start Period Date",
      },
      {
        name: "endPeriodDate",
        type: "string",
        nullable: true,
        description: "End Period Date",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Created By",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID: 1 for New, 3 for Authorized",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "canEdit",
        type: "boolean",
        nullable: true,
        description: "Flag whether data can be edited",
      },
    ],
  },
  {
    name: "employee_advance_payments",
    path: "/employee/employee-advance-payment",
    description: "Employee advance payments",
    mode: "paged",
    primaryKey: "employeeAdvanceNum",
    columns: [
      {
        name: "employeeAdvanceNum",
        type: "string",
        nullable: false,
        description: "Advance payment number with EA prefix",
      },
      {
        name: "employeeAdvanceDate",
        type: "date",
        nullable: true,
        description: "Advance payment date",
      },
      {
        name: "dueDay",
        type: "number",
        nullable: true,
        description: "Number of days until due",
      },
      {
        name: "employeeAdvanceDueDate",
        type: "date",
        nullable: true,
        description: "Due date",
      },
      {
        name: "employeeCode",
        type: "string",
        nullable: true,
        description: "Employee code",
      },
      {
        name: "employeeName",
        type: "string",
        nullable: true,
        description: "Employee name",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch name",
      },
      {
        name: "currencyID",
        type: "number",
        nullable: true,
        description: "Currency ID",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: "Currency sign",
      },
      {
        name: "employeeAdvanceTotal",
        type: "decimal",
        nullable: true,
        description: "Advance total amount",
      },
      {
        name: "rate",
        type: "decimal",
        nullable: true,
        description: "Exchange rate",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID: 1 for New, 2 for Rejected, 3 for Authorized, 27 for Released",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional information",
      },
    ],
  },
  {
    name: "goods_deliveries",
    path: "/inventory/goods-delivery",
    description: "Goods deliveries",
    mode: "paged",
    columns: [
      {
        name: "goodsDeliveryNum",
        type: "string",
        nullable: true,
        description: "Goods Delivery Number",
      },
      {
        name: "goodsDeliveryDate",
        type: "date",
        nullable: true,
        description: "Goods Delivery Date",
      },
      {
        name: "transType",
        type: "string",
        nullable: true,
        description: "Transaction Type",
      },
      {
        name: "referenceNumber",
        type: "string",
        nullable: true,
        description: "Reference Number",
      },
      {
        name: "originBranchID",
        type: "number",
        nullable: true,
        description: "Origin Branch ID",
      },
      {
        name: "originBranchName",
        type: "string",
        nullable: true,
        description: "Origin Branch Name",
      },
      {
        name: "destinationBranchID",
        type: "number",
        nullable: true,
        description: "Destination Branch ID",
      },
      {
        name: "destBranchName",
        type: "string",
        nullable: true,
        description: "Destination Branch Name",
      },
      {
        name: "customerName",
        type: "string",
        nullable: true,
        description: "Customer Name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
  {
    name: "goods_receipts",
    path: "/inventory/goods-receipt",
    description: "Goods receipts",
    mode: "paged",
    primaryKey: "goodsReceiptNum",
    columns: [
      {
        name: "goodsReceiptNum",
        type: "string",
        nullable: false,
        description: "Goods Receipt Number",
      },
      {
        name: "goodsReceiptDate",
        type: "date",
        nullable: true,
        description: "Goods Receipt Date",
      },
      {
        name: "linkGoodsReceiptNumEsbGoods",
        type: "string",
        nullable: true,
        description: "Goods Receipt Number ESB Goods",
      },
      {
        name: "refNum",
        type: "string",
        nullable: true,
        description: "Reference Number",
      },
      {
        name: "transType",
        type: "string",
        nullable: true,
        description: "Transaction Type",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "locationID",
        type: "number",
        nullable: true,
        description: "Location ID",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "sourceName",
        type: "string",
        nullable: true,
        description: "Source Name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Created By",
      },
    ],
  },
  {
    name: "goods_transfer_requests",
    path: "/inventory/goods-transfer-request",
    description: "Goods transfer requests",
    mode: "paged",
    primaryKey: "transferNum",
    columns: [
      {
        name: "transferNum",
        type: "string",
        nullable: false,
        description: "Goods Transfer Request Number",
      },
      {
        name: "transferDate",
        type: "date",
        nullable: true,
        description: "Goods Transfer Request Date",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "originBranch",
        type: "string",
        nullable: true,
        description: "Origin Branch",
      },
      {
        name: "destinationBranch",
        type: "string",
        nullable: true,
        description: "Destination Branch",
      },
      {
        name: "purchaseRequestNum",
        type: "string",
        nullable: true,
        description: "Purchase Request Number",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
  {
    name: "item_journals",
    path: "/inventory/item-journal",
    description: "Inventory item journals",
    mode: "paged",
    primaryKey: "itemJournalNum",
    columns: [
      {
        name: "itemJournalNum",
        type: "string",
        nullable: false,
        description: "Item Journal Number",
      },
      {
        name: "itemJournalDate",
        type: "datetime",
        nullable: true,
        description: "Item Journal Date in ISO 8601 format with timezone",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "locationID",
        type: "number",
        nullable: true,
        description: "Location ID",
      },
      {
        name: "locationName",
        type: "string",
        nullable: true,
        description: "Location Name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
  {
    name: "purposes",
    path: "/purpose",
    description: "Accounting purposes",
    mode: "paged",
    primaryKey: "purposeID",
    columns: [
      {
        name: "purposeID",
        type: "number",
        nullable: false,
        description: "Purpose ID",
      },
      {
        name: "purposeName",
        type: "string",
        nullable: true,
        description: "Purpose Name",
      },
      {
        name: "purposeAccount",
        type: "string",
        nullable: true,
        description: "Account Name on purpose",
      },
      {
        name: "flagActive",
        type: "boolean",
        nullable: true,
        description: "Flag setting for Active or not Purpose",
      },
    ],
  },
  {
    name: "bills_of_material",
    path: "/product/bom",
    description: "Bills of material",
    mode: "paged",
    primaryKey: "bomID",
    columns: [
      {
        name: "bomID",
        type: "number",
        nullable: false,
        description: "Bill of Material ID",
      },
      {
        name: "bomName",
        type: "string",
        nullable: true,
        description: "Bill of Material Name",
      },
      {
        name: "bomCode",
        type: "string",
        nullable: true,
        description: "Bill of Material Code",
      },
      {
        name: "bomTypeID",
        type: "number",
        nullable: true,
        description: "Bill of Material Type ID",
      },
      {
        name: "bomTypeName",
        type: "string",
        nullable: true,
        description: "Bill of Material Type Name",
      },
      {
        name: "productName",
        type: "string",
        nullable: true,
        description: "Product Name",
      },
      {
        name: "uomName",
        type: "string",
        nullable: true,
        description: "Unit of Material Name",
      },
      {
        name: "notes",
        type: "string",
        nullable: true,
        description: "Bill of Material notes",
      },
      {
        name: "flagActive",
        type: "number",
        nullable: true,
        description: "Flag setting for Active or not Bill of Material - 1: Active - 0: Not Active",
      },
    ],
  },
  {
    name: "categories",
    path: "/product/category",
    description: "Product categories",
    mode: "paged",
    primaryKey: "categoryID",
    columns: [
      {
        name: "categoryID",
        type: "number",
        nullable: false,
        description: "Category ID",
      },
      {
        name: "categoryName",
        type: "string",
        nullable: true,
        description: "Category Name",
      },
      {
        name: "categoryTypeID",
        type: "number",
        nullable: true,
        description: "Category Type ID",
      },
      {
        name: "categoryTypeName",
        type: "string",
        nullable: true,
        description: "Category Type Name",
      },
      {
        name: "notes",
        type: "string",
        nullable: true,
        description: "Category notes",
      },
      {
        name: "flagActive",
        type: "number",
        nullable: true,
        description: "Flag setting for Active or not Category - 1: Active - 0: Not Active",
      },
    ],
  },
  {
    name: "branches",
    path: "/branch",
    description: "Branches available to the authenticated ESB company",
    mode: "direct",
    primaryKey: "branchID",
    columns: [
      {
        name: "branchID",
        type: "number",
        nullable: false,
        description: "Branch ID",
      },
      {
        name: "branchCode",
        type: "string",
        nullable: true,
        description: "Branch Code",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
    ],
  },
  {
    name: "locations",
    path: "/location",
    description: "Inventory locations",
    mode: "direct",
    primaryKey: "locationID",
    columns: [
      {
        name: "locationID",
        type: "number",
        nullable: false,
        description: "Location ID",
      },
      {
        name: "locationName",
        type: "string",
        nullable: true,
        description: "Location Name",
      },
    ],
  },
  {
    name: "cost_centers",
    path: "/cost-center",
    description: "Cost centers",
    mode: "direct",
    primaryKey: "ID",
    columns: [
      {
        name: "ID",
        type: "number",
        nullable: false,
        description: "Cost Center ID",
      },
      {
        name: "costCenter",
        type: "string",
        nullable: true,
        description: "Cost Center Code",
      },
      {
        name: "costCenterName",
        type: "string",
        nullable: true,
        description: "Cost Center Name",
      },
      {
        name: "flagActive",
        type: "boolean",
        nullable: true,
        description: "Flag setting for Active or not Cost Center",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Username who create cost center",
      },
      {
        name: "createdDate",
        type: "datetime",
        nullable: true,
        description: "Date and time cost center created",
      },
      {
        name: "editedBy",
        type: "string",
        nullable: true,
        description: "Username who edited cost center last time",
      },
      {
        name: "editedDate",
        type: "datetime",
        nullable: true,
        description: "Date and time cost center last edited",
      },
    ],
  },
  {
    name: "customer_pricelists",
    path: "/customer-pricelist",
    description: "Customer price lists",
    mode: "paged",
    primaryKey: "ID",
    columns: [
      {
        name: "ID",
        type: "number",
        nullable: false,
        description: "Customer Pricelist ID",
      },
      {
        name: "priceDate",
        type: "datetime",
        nullable: true,
        description: "Customer Pricelist active date",
      },
      {
        name: "customerName",
        type: "string",
        nullable: true,
        description: "Customer Name",
      },
      {
        name: "productName",
        type: "string",
        nullable: true,
        description: "Product Name",
      },
      {
        name: "productCode",
        type: "string",
        nullable: true,
        description: "Product Code",
      },
      {
        name: "uomName",
        type: "string",
        nullable: true,
        description: "Unit name",
      },
      {
        name: "currencyName",
        type: "string",
        nullable: true,
        description: "Currency Name",
      },
      {
        name: "expireDate",
        type: "datetime",
        nullable: true,
        description: "Expire Date",
      },
      {
        name: "price",
        type: "number",
        nullable: true,
        description: "Customer Pricelist product price",
      },
    ],
  },
  {
    name: "customers",
    path: "/customer",
    description: "Customers",
    mode: "paged",
    primaryKey: "customerID",
    columns: [
      {
        name: "customerID",
        type: "number",
        nullable: false,
        description: "Customer ID",
      },
      {
        name: "customerName",
        type: "string",
        nullable: true,
        description: "Customer Name",
      },
      {
        name: "customerCode",
        type: "string",
        nullable: true,
        description: "Customer Code",
      },
      {
        name: "customerCategoryID",
        type: "string",
        nullable: true,
        description: "Customer Category ID",
      },
      {
        name: "customerCategoryName",
        type: "string",
        nullable: true,
        description: "Customer Category Name",
      },
      {
        name: "paymentDueDays",
        type: "number",
        nullable: true,
        description: "Payment Due Days",
      },
      {
        name: "address",
        type: "string",
        nullable: true,
        description: "Customer Address",
      },
      {
        name: "picName",
        type: "string",
        nullable: true,
        description: "PIC Name",
      },
      {
        name: "picPhone",
        type: "string",
        nullable: true,
        description: "PIC Phone",
      },
      {
        name: "flagActive",
        type: "boolean",
        nullable: true,
        description: "Flag setting for Active or not Customer",
      },
      {
        name: "lockVat",
        type: "boolean",
        nullable: true,
        description: "Flag setting for lock Vat in transaction",
      },
    ],
  },
  {
    name: "document_templates",
    path: "/document-template",
    description: "Document templates",
    mode: "paged",
    primaryKey: "requestTemplateID",
    columns: [
      {
        name: "requestTemplateID",
        type: "number",
        nullable: false,
        description: "Request Template ID",
      },
      {
        name: "requestTemplateName",
        type: "string",
        nullable: true,
        description: "Request Template Name",
      },
      {
        name: "branchNames",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "flagActive",
        type: "number",
        nullable: true,
        description: "Flag setting for Active or not Bill of Material - 1: Active - 0: Not Active",
      },
    ],
  },
  {
    name: "pricelists",
    path: "/pricelist",
    description: "Supplier price lists",
    mode: "paged",
    primaryKey: "ID",
    columns: [
      {
        name: "ID",
        type: "number",
        nullable: false,
        description: "Pricelist ID",
      },
      {
        name: "priceDate",
        type: "date",
        nullable: true,
        description: "Pricelist active date",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "productName",
        type: "string",
        nullable: true,
        description: "Product Name",
      },
      {
        name: "productCode",
        type: "string",
        nullable: true,
        description: "Product Code",
      },
      {
        name: "unit",
        type: "string",
        nullable: true,
        description: "Unit name",
      },
      {
        name: "currencyName",
        type: "string",
        nullable: true,
        description: "Currency Name",
      },
      {
        name: "price",
        type: "number",
        nullable: true,
        description: "Pricelist product price",
      },
    ],
  },
  {
    name: "products",
    path: "/product/list",
    description: "Products",
    mode: "paged",
    primaryKey: "productID",
    columns: [
      {
        name: "productID",
        type: "number",
        nullable: false,
        description: "Product ID",
      },
      {
        name: "productName",
        type: "string",
        nullable: true,
        description: "Product Name",
      },
      {
        name: "productCode",
        type: "string",
        nullable: true,
        description: "Product Code",
      },
      {
        name: "categoryID",
        type: "number",
        nullable: true,
        description: "Category Type ID",
      },
      {
        name: "subCategoryID",
        type: "number",
        nullable: true,
        description: "Sub Category ID",
      },
      {
        name: "subCategoryName",
        type: "string",
        nullable: true,
        description: "Sub Category Name",
      },
      {
        name: "bomID",
        type: "number",
        nullable: true,
        description: "Bill of Material ID",
      },
      {
        name: "bomName",
        type: "string",
        nullable: true,
        description: "Bill of Material Name",
      },
      {
        name: "categoryTypeID",
        type: "number",
        nullable: true,
        description: "Category Type ID",
      },
      {
        name: "categoryTypeName",
        type: "string",
        nullable: true,
        description: "Category Type Name",
      },
      {
        name: "flagActive",
        type: "number",
        nullable: true,
        description: "Flag setting for Active or not Bill of Material - 1: Active - 0: Not Active",
      },
      { name: "categoryName", type: "string", nullable: true, description: "" },
    ],
  },
  {
    name: "subcategories",
    path: "/product/sub-category",
    description: "Product subcategories",
    mode: "paged",
    primaryKey: "subCategoryID",
    columns: [
      {
        name: "subCategoryID",
        type: "number",
        nullable: false,
        description: "Sub Category ID",
      },
      {
        name: "subCategoryName",
        type: "string",
        nullable: true,
        description: "Sub Category Name",
      },
      {
        name: "notes",
        type: "string",
        nullable: true,
        description: "Sub Category notes",
      },
      {
        name: "flagActive",
        type: "number",
        nullable: true,
        description: "Flag setting for Active or not Category - 1: Active - 0: Not Active",
      },
    ],
  },
  {
    name: "supplier_categories",
    path: "/supplier/category/list",
    description: "Supplier categories",
    mode: "paged",
    primaryKey: "supplierCategoryID",
    columns: [
      {
        name: "supplierCategoryID",
        type: "number",
        nullable: false,
        description: "Supplier Category ID",
      },
      {
        name: "supplierCategoryName",
        type: "string",
        nullable: true,
        description: "Supplier Category Name",
      },
      {
        name: "flagActive",
        type: "number",
        nullable: true,
        description: "Flag setting for Active or not Supplier Category: 1 Active, 0 Not Active",
      },
    ],
  },
  {
    name: "suppliers",
    path: "/supplier",
    description: "Suppliers",
    mode: "paged",
    primaryKey: "supplierID",
    columns: [
      {
        name: "supplierID",
        type: "number",
        nullable: false,
        description: "Supplier ID",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "address",
        type: "string",
        nullable: true,
        description: "Supplier Address",
      },
      {
        name: "supplierCode",
        type: "string",
        nullable: true,
        description: "Supplier Code",
      },
      {
        name: "dueDate",
        type: "number",
        nullable: true,
        description: "Credit Terms in Days",
      },
      {
        name: "flagActive",
        type: "boolean",
        nullable: true,
        description: "Flag setting for Active or not Supplier Category",
      },
      {
        name: "contactPerson",
        type: "string",
        nullable: true,
        description: "Supplier PIC Name",
      },
      {
        name: "cellPhone",
        type: "string",
        nullable: true,
        description: "Supplier PIC Phone Number",
      },
      {
        name: "category",
        type: "string",
        nullable: true,
        description: "Supplier Category Name",
      },
      {
        name: "supplierCategoryID",
        type: "number",
        nullable: true,
        description: "Supplier Category ID",
      },
    ],
  },
  {
    name: "units",
    path: "/units",
    description: "Units of measure",
    mode: "direct",
    primaryKey: "uomID",
    columns: [
      {
        name: "uomID",
        type: "number",
        nullable: false,
        description: "Unit of Material ID",
      },
      {
        name: "uomName",
        type: "string",
        nullable: true,
        description: "Unit of Material Name",
      },
    ],
  },
  {
    name: "material_deliveries",
    path: "/production/material-delivery",
    description: "Production material deliveries",
    mode: "paged",
    primaryKey: "materialDeliveryNum",
    columns: [
      {
        name: "materialDeliveryNum",
        type: "string",
        nullable: false,
        description: "Material Delivery Number",
      },
      {
        name: "materialDeliveryDate",
        type: "datetime",
        nullable: true,
        description: "Material Delivery Date",
      },
      {
        name: "productionOrderNum",
        type: "string",
        nullable: true,
        description: "Production Order Number",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
  {
    name: "memorial_journals",
    path: "/accounting/memorial-journal",
    description: "Memorial journals",
    mode: "paged",
    primaryKey: "memorialJournalNum",
    columns: [
      {
        name: "memorialJournalNum",
        type: "string",
        nullable: false,
        description: "Memorial Journal number with MJ prefix",
      },
      {
        name: "memorialJournalDate",
        type: "datetime",
        nullable: true,
        description: "Memorial Journal date",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID: 1 for New, 2 for Rejected, 3 for Authorized, 38 for Waiting For Approval",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Creator username",
      },
      {
        name: "approval",
        type: "boolean",
        nullable: true,
        description: "Whether approval flow is configured for this transaction",
      },
    ],
  },
  {
    name: "production_orders",
    path: "/production/production-order",
    description: "Production orders",
    mode: "paged",
    primaryKey: "productionOrderNum",
    columns: [
      {
        name: "productionOrderNum",
        type: "string",
        nullable: false,
        description: "Production Order Number",
      },
      {
        name: "productionOrderDate",
        type: "datetime",
        nullable: true,
        description: "Production Order Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "bomTypeID",
        type: "number",
        nullable: true,
        description: "Bill of material type ID",
      },
      {
        name: "bomTypeName",
        type: "string",
        nullable: true,
        description: "Bill of material type name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
  {
    name: "production_results",
    path: "/production/production-result",
    description: "Production results",
    mode: "paged",
    primaryKey: "productionResultNum",
    columns: [
      {
        name: "productionResultNum",
        type: "string",
        nullable: false,
        description: "Production Result Number",
      },
      {
        name: "productionResultDate",
        type: "datetime",
        nullable: true,
        description: "Production Result Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "productionOrderDetailID",
        type: "number",
        nullable: true,
        description: "Production Order Detail ID",
      },
      {
        name: "productionOrderNum",
        type: "string",
        nullable: true,
        description: "Production Result Number",
      },
      {
        name: "bomID",
        type: "number",
        nullable: true,
        description: "Bill of material ID",
      },
      {
        name: "bomName",
        type: "string",
        nullable: true,
        description: "Bill of material name",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
    ],
  },
  {
    name: "purchase_invoices",
    path: "/purchase/purchase-invoices",
    description: "Purchase invoices",
    mode: "paged",
    primaryKey: "purchaseInvoiceNum",
    columns: [
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Username who created the record",
      },
      {
        name: "createdByFullName",
        type: "string",
        nullable: true,
        description: "Full name of the user who created the record",
      },
      {
        name: "currencyID",
        type: "number",
        nullable: true,
        description: "Currency ID",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: 'Currency Symbol, such as "IDR" or "USD"',
      },
      {
        name: "invoiceTotal",
        type: "number",
        nullable: true,
        description: "Total invoice amount",
      },
      {
        name: "linkInvoiceNumEsbGoods",
        type: "string",
        nullable: true,
        description: "Linked ESB Goods Invoice Number when available",
      },
      {
        name: "overDue",
        type: "number",
        nullable: true,
        description: "Days overdue from due date",
      },
      {
        name: "purchaseInvoiceDate",
        type: "date",
        nullable: true,
        description: "Purchase Invoice Date",
      },
      {
        name: "purchaseInvoiceDueDate",
        type: "date",
        nullable: true,
        description: "Purchase Invoice Due Date",
      },
      {
        name: "purchaseInvoiceNum",
        type: "string",
        nullable: false,
        description: "Purchase Invoice Number",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: 'Status Name, such as "New", "Authorized", "Rejected", "Full Paid", or "Draft"',
      },
      {
        name: "supplierID",
        type: "number",
        nullable: true,
        description: "Supplier ID",
      },
      {
        name: "supplierInvoiceNum",
        type: "string",
        nullable: true,
        description: "Supplier Invoice Number when available",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional information",
      },
    ],
  },
  {
    name: "purchase_orders",
    path: "/purchase/purchase-order",
    description: "Purchase orders",
    mode: "paged",
    primaryKey: "purchaseNum",
    columns: [
      {
        name: "purchaseNum",
        type: "string",
        nullable: false,
        description: "Purchase Order Number",
      },
      {
        name: "purchaseDate",
        type: "datetime",
        nullable: true,
        description: "Purchase Order Date",
      },
      {
        name: "requiredDate",
        type: "datetime",
        nullable: true,
        description: "Purchase Order Required Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "supplierID",
        type: "number",
        nullable: true,
        description: "Supplier ID",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "currencyID",
        type: "number",
        nullable: true,
        description: "Currency ID",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: "Currency Sign",
      },
      {
        name: "purchaseRequestNums",
        type: "string",
        nullable: true,
        description: "Purchase Request Number",
      },
      {
        name: "linkPurchaseNumEsbGoods",
        type: "string",
        nullable: true,
        description: "Link Purchase ESB Goods",
      },
      {
        name: "purchaseTotal",
        type: "decimal",
        nullable: true,
        description: "",
      },
      {
        name: "printedBy",
        type: "string",
        nullable: true,
        description: "Printed By",
      },
      {
        name: "printedDate",
        type: "string",
        nullable: true,
        description: "Printed Date",
      },
      {
        name: "emailedBy",
        type: "string",
        nullable: true,
        description: "Emailed By",
      },
      {
        name: "emailedDate",
        type: "datetime",
        nullable: true,
        description: "Emailed Date",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Info",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "approval",
        type: "string",
        nullable: true,
        description: "Approval",
      },
      {
        name: "mapSupplierLink",
        type: "string",
        nullable: true,
        description: "Map Supplier Link",
      },
    ],
  },
  {
    name: "purchase_requests",
    path: "/purchase/purchase-request",
    description: "Purchase requests",
    mode: "paged",
    primaryKey: "purchaseRequestNum",
    columns: [
      {
        name: "purchaseRequestNum",
        type: "string",
        nullable: false,
        description: "Purchase Request Number",
      },
      {
        name: "purchaseRequestDate",
        type: "date",
        nullable: true,
        description: "Purchase Request Date",
      },
      {
        name: "requiredDate",
        type: "date",
        nullable: true,
        description: "Required Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "createdDate",
        type: "date",
        nullable: true,
        description: "Created Date",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "requestTemplateID",
        type: "number",
        nullable: true,
        description: "Request Template ID",
      },
    ],
  },
  {
    name: "purchase_returns",
    path: "/purchases/purchase-return",
    description: "Purchase returns",
    mode: "paged",
    primaryKey: "purchaseReturnNum",
    columns: [
      {
        name: "purchaseReturnNum",
        type: "string",
        nullable: false,
        description: "Purchase Return Number",
      },
      {
        name: "purchaseReturnDate",
        type: "date",
        nullable: true,
        description: "Purchase Return Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "supplierID",
        type: "number",
        nullable: true,
        description: "Supplier ID",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: 'Status Name, such as "New", "Rejected", "Authorized", "Full Paid", or "Draft"',
      },
    ],
  },
  {
    name: "receipts",
    path: "/receipt",
    description: "Customer receipts",
    mode: "paged",
    primaryKey: "receiptNum",
    columns: [
      {
        name: "receiptNum",
        type: "string",
        nullable: false,
        description: "Receipt Number",
      },
      {
        name: "receiptDate",
        type: "date",
        nullable: true,
        description: "Receipt Date",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "customerName",
        type: "string",
        nullable: true,
        description: "Customer Name",
      },
      {
        name: "paymentType",
        type: "string",
        nullable: true,
        description: "Type of Payment",
      },
      {
        name: "grandTotal",
        type: "decimal",
        nullable: true,
        description: "Grand Total Receipt",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "hasApproval",
        type: "boolean",
        nullable: true,
        description: "Receipt has approval or not",
      },
    ],
  },
  {
    name: "sales_orders",
    path: "/sales/product-sales",
    description: "Sales orders",
    mode: "paged",
    primaryKey: "productSalesNum",
    columns: [
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Info",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "createdBy",
        type: "string",
        nullable: true,
        description: "Username who create Sales Order",
      },
      {
        name: "customerAddress",
        type: "string",
        nullable: true,
        description: "Customer Address",
      },
      {
        name: "customerID",
        type: "number",
        nullable: true,
        description: "Customer ID",
      },
      {
        name: "customerName",
        type: "string",
        nullable: true,
        description: "Customer Name",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: "Currency Sign",
      },
      {
        name: "linkPurchaseNum",
        type: "string",
        nullable: true,
        description: "Reference Number",
      },
      {
        name: "productSalesTypeID",
        type: "number",
        nullable: true,
        description: "Sales Order Type ID",
      },
      {
        name: "requiredDate",
        type: "date",
        nullable: true,
        description: "Sales Order Required Date",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "productSalesDate",
        type: "date",
        nullable: true,
        description: "Sales Order Date",
      },
      {
        name: "productSalesNum",
        type: "string",
        nullable: false,
        description: "Sales Order Number",
      },
      {
        name: "productSalesTotal",
        type: "decimal",
        nullable: true,
        description: "Sales Order Total",
      },
    ],
  },
  {
    name: "simple_manufacturing",
    path: "/production/simple-manufacturing",
    description: "Simple manufacturing transactions",
    mode: "paged",
    primaryKey: "simpleManufacturingNum",
    columns: [
      {
        name: "simpleManufacturingNum",
        type: "string",
        nullable: false,
        description: "Simple Manufacturing Number",
      },
      {
        name: "simpleManufacturingDate",
        type: "datetime",
        nullable: true,
        description: "Simple Manufacturing Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "bomTypeID",
        type: "number",
        nullable: true,
        description: "Bill of Material Type ID",
      },
      {
        name: "bomTypeName",
        type: "string",
        nullable: true,
        description: "Bill of Material Type Name",
      },
      {
        name: "bomID",
        type: "number",
        nullable: true,
        description: "Bill of Material ID",
      },
      {
        name: "bomName",
        type: "string",
        nullable: true,
        description: "Bill of Material Name",
      },
      {
        name: "bomCode",
        type: "string",
        nullable: true,
        description: "Bill of Material Code",
      },
      {
        name: "manufacturingQty",
        type: "decimal",
        nullable: true,
        description: "Manufacturing Quantity",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
  {
    name: "simple_purchases",
    path: "/purchase/simple-purchase",
    description: "Simple purchase transactions",
    mode: "paged",
    primaryKey: "cashPurchaseNum",
    columns: [
      {
        name: "cashPurchaseNum",
        type: "string",
        nullable: false,
        description: "Simple Purchase Number",
      },
      {
        name: "cashPurchaseDate",
        type: "datetime",
        nullable: true,
        description: "Simple Purchase Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "supplierID",
        type: "number",
        nullable: true,
        description: "Supplier ID",
      },
      {
        name: "supplierName",
        type: "string",
        nullable: true,
        description: "Supplier Name",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: "Currency Name",
      },
      {
        name: "cashPurchaseTotal",
        type: "decimal",
        nullable: true,
        description: "Cash Purchase Total",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "approval",
        type: "string",
        nullable: true,
        description: "Approval",
      },
    ],
  },
  {
    name: "simple_sales",
    path: "/sales/simple-product-sales",
    description: "Simple sales transactions",
    mode: "paged",
    primaryKey: "simpleProductSalesNum",
    columns: [
      {
        name: "simpleProductSalesNum",
        type: "string",
        nullable: false,
        description: "Simple Sales Number",
      },
      {
        name: "simpleProductSalesDate",
        type: "datetime",
        nullable: true,
        description: "Transaction Date",
      },
      {
        name: "branchID",
        type: "number",
        nullable: true,
        description: "Branch ID",
      },
      {
        name: "branchName",
        type: "string",
        nullable: true,
        description: "Branch Name",
      },
      {
        name: "customerID",
        type: "number",
        nullable: true,
        description: "Customer ID",
      },
      {
        name: "customerName",
        type: "string",
        nullable: true,
        description: "Customer Name",
      },
      {
        name: "simpleProductSalesTotal",
        type: "decimal",
        nullable: true,
        description: "Transaction Total Amount",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
      {
        name: "currencySign",
        type: "string",
        nullable: true,
        description: "Currency Sign",
      },
      {
        name: "vatInvoiceNum",
        type: "string",
        nullable: true,
        description: "VAT Invoice Number",
      },
      {
        name: "paymentID",
        type: "number",
        nullable: true,
        description: "Payment Type ID",
      },
      {
        name: "paymentName",
        type: "string",
        nullable: true,
        description: "Payment Type Name",
      },
    ],
  },
  {
    name: "simple_transfers",
    path: "/simple-transfer",
    description: "Simple inventory transfers",
    mode: "paged",
    primaryKey: "simpleTransferNum",
    columns: [
      {
        name: "simpleTransferNum",
        type: "string",
        nullable: false,
        description: "Simple Transfer Number",
      },
      {
        name: "simpleTransferDate",
        type: "date",
        nullable: true,
        description: "Simple Transfer Date",
      },
      {
        name: "originLocationName",
        type: "string",
        nullable: true,
        description: "Origin Location name",
      },
      {
        name: "destinationLocationName",
        type: "string",
        nullable: true,
        description: "Destination Location Name",
      },
      {
        name: "destinationLocationID",
        type: "number",
        nullable: true,
        description: "Destination Location ID",
      },
      {
        name: "additionalInfo",
        type: "string",
        nullable: true,
        description: "Additional Information",
      },
      {
        name: "statusID",
        type: "number",
        nullable: true,
        description: "Status ID",
      },
      {
        name: "statusName",
        type: "string",
        nullable: true,
        description: "Status Name",
      },
    ],
  },
];

export function validateEsbCoreCatalog(catalog: EsbCoreObject[] = ESB_CORE_CATALOG): void {
  const names = new Set<string>();
  for (const object of catalog) {
    if (names.has(object.name)) throw new Error(`duplicate ESB Core table '${object.name}'`);
    names.add(object.name);

    const fields = new Set<string>();
    for (const column of object.columns) {
      if (fields.has(column.name)) {
        throw new Error(`duplicate ESB Core field '${object.name}.${column.name}'`);
      }
      fields.add(column.name);
    }
    if (object.primaryKey && !fields.has(object.primaryKey)) {
      throw new Error(`ESB Core primary key '${object.name}.${object.primaryKey}' is not a declared field`);
    }
  }
}

validateEsbCoreCatalog();
